### ISSUE TITLE
Cloud Architecture Design

### ISSUE THREAD

**Issue by koufopoulosf** [serverlessmaps/serverlessmaps#1]
Hey there! 👋

I just wanted to drop a quick thank you for sharing your awesome repo and the inspiring [article](https://tobilg.com/serverless-maps-for-fun-and-profit)!

I've got a question about your choice of CloudFront over Cloudflare. I noticed Protomaps leans towards Cloudflare because of the cost factor with CloudFront in an [AWS setup](https://docs.protomaps.com/deploy/cost). So, I'm curious, is there something I'm missing here?

Thanks a bunch for your time!

Cheers,

Filippos

**Comment by tobilg** [comment]
Thanks for reaching out! I don't think the linked comparison is accurate, as CloudFront has a free tier of 1TB outgoing traffic per month, see https://aws.amazon.com/blogs/aws/aws-free-tier-data-transfer-expansion-100-gb-from-regions-and-1-tb-from-amazon-cloudfront-per-month/ In the comparison, the 1000GB traffic is listed with $100...

Also, I'm using AWS because that's where I'm an expert in, other people might use Cloudflare or other providers as they desire.

**Comment by koufopoulosf** [comment]
Hi @tobilg,

I must say, the 1TB of outgoing traffic per month is quite appealing. I overlooked that detail earlier.

Do you believe the current setup of this repository is production-ready? Are there any areas you think could be enhanced to improve its readiness? If you're open to freelancing opportunities, I'd greatly appreciate your assistance for my use case :)

Thank you for your valuable feedback in advance!

**Comment by tobilg** [comment]
I guess the answer is "it depends", as I don't know what you exactly define as "production-ready". Could you elaborate a bit, as well as describing your use case?

**Comment by koufopoulosf** [comment]
I'm interested in using a customizable basemap that can look beautiful, similar to the screenshot you have in this repo. Was it like that by default, or did you customize it to look that way? The map needs to be planet scale, and in my use case will be used in a mobile app where I will simply display POIs.

Additionally, by 'production ready,' I meant something secure in terms of policies that prevent bots from making endless requests. Is this repo already optimized for that, or could it be improved further, perhaps by following the practices described by [Protomaps](https://docs.protomaps.com/deploy/aws)?

**Comment by tobilg** [comment]
It's all in the repo, the screenshot is taken from https://github.com/serverlessmaps/serverlessmaps/blob/main/website/index.html once deployed to CloudFront.

Similarly, the IaC is found in https://github.com/serverlessmaps/serverlessmaps/tree/main/iac which you can review yourself in case you want to check if it _really_ adheres to the Protomaps recommendations. Regarding bot mitigation, you can place a WAF in front of CloudFront (see e.g. https://cloudjourney.medium.com/aws-cloudfront-and-waf-97d7314b07af), but this is not built-in to the IaC because potential costs.

Don't get me wrong, but this is an Open Source project that is provided free of charge, meaning that I can't give you free customer support.

**Comment by koufopoulosf** [comment]
That's why I asked previously if you are open to freelancing opportunities :)

Thanks for your detailed reply once again!
